import { NextResponse } from 'next/server';
import { post, AppsScriptError } from '@/lib/api';

export const maxDuration = 60;

/** Vercel Cron — daily quota check at 8 AM Bangkok (1 AM UTC).
 *
 *  Replaces the Apps Script time trigger of the same function. Calls Apps
 *  Script `runQuotaCheck` action which runs `dailyQuotaCheck()` (synthetic
 *  loadOrder timing + sheet sanity → LINE alert if 🟡 or 🔴).
 *
 *  Scheduled in [vercel.json](vercel.json) — `"0 1 * * *"`.
 *
 *  Auth: Vercel automatically injects `Authorization: Bearer ${CRON_SECRET}`
 *  header. Without it, the route returns 401 (so cron URL isn't publicly
 *  abusable). CRON_SECRET is auto-generated by Vercel when first cron added,
 *  visible in Project Settings → Environment Variables.
 *
 *  Once verified working, user must delete the corresponding Apps Script
 *  time trigger (Apps Script editor → Triggers → delete row for
 *  `dailyQuotaCheck`) to avoid double-firing.
 */
export async function GET(req: Request) {
  const auth = req.headers.get('authorization');
  if (auth !== `Bearer ${process.env.CRON_SECRET}`) {
    return new Response('Unauthorized', { status: 401 });
  }

  try {
    const result = await post<{ ok?: boolean; error?: string }>('runQuotaCheck', {});
    if (result.error) {
      return NextResponse.json({ error: result.error }, { status: 502 });
    }
    return NextResponse.json({ ok: true, ranAt: new Date().toISOString() });
  } catch (err) {
    const msg = err instanceof AppsScriptError ? err.message : err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: msg }, { status: 502 });
  }
}
